### ISSUE TITLE
All features example is not working

### ISSUE THREAD

**Issue by Awilum** [elninotech/uppload#86] opened 2020-02-13 07:09 UTC
from this page https://uppload.js.org/examples - **All features**

https://codesandbox.io/s/jovial-sky-dm7cm

```
TypeError
Cannot call a class constructor without |new|
```

**Comment by AnandChowdhary** [comment] 2020-02-13 09:13
Thanks for opening this issue, @Awilum! We saw that a few of these examples aren't working, and I'll make sure they're back later today (with a better git-based examples system).

This is a duplicate of #79

**Closed by AnandChowdhary** 2020-02-13 09:13 UTC
Labels: duplicate, enhancement

**Comment by dtbaker** [comment] 2021-05-31 11:24
Heya @AnandChowdhary is this examples page working?

![image](https://user-images.githubusercontent.com/543073/120186166-7a507000-c256-11eb-8814-fc0076fccf53.png)


The links in the example monorepo don't seem to take me anywhere useful either: 


It just feels like the demos should be visible one after the other on that page but they're not :shrug:
